<?php 

$row = $this->row;

?>                            
                            <div class="container position-relative mt-4">
                                <div class="jumbotron px-4 pt-3 rounded bg-white shadow-sm">
                                    <div class="row">
                                        <div class="col-lg-6 col-12">
                                            <p class="bread_cat"><strong> Data List </strong></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="active_list">
            <div class="container">
                <div class="jumbotron bg-white shadow-sm px-3 py-3 rounded">
                    <div class="row pb-3">
                        <div class="col-lg-6 col-md-6 col-6">
                            <div class="col-auto">
                                    <p class="row_count">Displaying <strong>1-10</strong> of <strong>40</strong> </p>
                                </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-6">
                            <div class="row">
                                <div class="col-auto">
                                    <select class="form-select" aria-label="Default select example">
                                        <option value="1">1</option>
                                        <option value="2">10</option>
                                        <option value="3">25</option>
                                        <option value="3">100</option>
                                    </select>
                                </div>
                                <div class="col-auto">
                                    <form class="d-flex">
                                        <input class="form-control me-1" type="search" placeholder="Search" aria-label="Search">
                                        <button class="btn btn-outline-success text-gray-dark" type="submit"><i class="fas fa-search"></i></button>
                                        <button class="btn btn-outline-success text-gray-dark" type="submit"><i class="fas fa-times"></i></button>
                                    </form>
                                </div>
                                <div class="col-auto">
                                    <a href="#"><p class="row_count text-warning mx-1"><i class="fas fa-sliders-h text-warning"></i> Advance Search</p></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive" >
                        <table class="table table-bordered " id="myTable">
                            <thead>
                                <tr class="text-capitalize text-center">
                                    <th scope="col"><span class="th_name">Image</span></th>
                                    <th scope="col"><span class="th_name">Name</span></th>
                                    <th scope="col"><span class="th_name">Slug</span></th>
                                    <th scope="col"><span class="th_name">Parent Category</span></th>
                                    <th scope="col"><span class="th_name">Group Categories</span></th>
                                    <th scope="col"><span class="th_name">Filterable Attributes</span></th>
                                    <th scope="col"><span class="th_name">Keywords</span></th>
                                    <th scope="col"><span class="th_name">Featured Brands</span></th>
                                    <th scope="col"><span class="th_name">Meta Image</span></th>
                                    <th scope="col"><span class="th_name">Meta Title</span></th>
                                    <th scope="col"><span class="th_name">Meta Description</span></th>
                                    <th scope="col"><span class="th_name">Meta Keywords</span></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                    foreach ($row as $rows) {
                                    $image = $rows['image'];
                                    $name = $rows['name'];
                                    $slug = $rows['slug'];
                                    $parent_category = $rows['parent_category'];
                                    $group_category = $rows['group_category'];
                                    $filterable_attributes = $rows['filterable_attributes'];
                                    $keywords = $rows['keywords'];
                                    $featured_brands = $rows['featured_brands'];
                                    $meta_image = $rows['meta_image'];
                                    $meta_title = $rows['meta_title'];
                                    $meta_description = $rows['meta_description'];
                                    $meta_keywords = $rows['meta_keywords'];
                                ?>
                                <tr class="text-capitalize text-center">
                                    <td><span class="td_name"> <?php echo "<img src='$image' class='w-100 img-fluid shadow rounded'>"?></span></td>
                                    <td><span class="td_name"> <?php echo $name; ?> </span></td>
                                    <td><span class="td_name"> <?php echo $slug; ?> </span></td>
                                    <td><span class="td_name"> <?php echo $parent_category; ?> </span></td>
                                    <td><span class="td_name"> <?php echo $group_category; ?> </span></td>
                                    <td><span class="td_name"> <?php echo $filterable_attributes; ?> </span></td>
                                    <td><span class="td_name"> <?php echo $keywords; ?> </span></td>
                                    <td><span class="td_name"> <?php echo "<img src='$featured_brands' class='w-100 img-fluid shadow rounded'>"?></span></td>
                                    <td><span class="td_name"> <?php echo "<img src='$meta_image' class='w-100 img-fluid shadow rounded'>"?></span></td>
                                    <td><span class="td_name"> <?php echo $meta_title; ?> </span></td>
                                    <td><span class="td_name"> <?php echo $meta_description; ?> </span></td>
                                    <td><span class="td_name"> <?php echo $meta_keywords; ?> </span></td>
                                </tr>
                            <?php } ?>
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
       