<?php
$current_controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$current_action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

$session = Core_WC_Session::get();

?><!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<link rel="shortcut icon" type="image/x-icon" href="/assets/favicon.ico">
	<title>Web Cables</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
	<meta content="" name="description"/>
	<meta content="" name="author"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="<?= $current_controller.$current_action=="userlogin"?"login":"page-header-fixed page-full-width" ?>">

	<!-- BEGIN CONTAINER -->
	<div id="page_container" class="page-container" <?= $this->noheader?"style='margin-top:0px!important'":"" ?>>
		<!-- BEGIN CONTENT -->
		<div class="page-content-wrapper">
			<div class="page-content">
				<!-- BEGIN PAGE CONTENT-->
				<div class='row'><div class='col-md-12'><?=$this->SubMenu?></div></div>
				<div class="row">
					<div class="col-md-12">
						<? echo $this->layout()->content; ?>
					</div>
				</div>
				<!-- END PAGE CONTENT-->
			</div>
		</div>
		<!-- END CONTENT -->
		
	</div>
	<!-- END CONTAINER -->
	<?
	if(!$this->nofooter) { ?>
	<!-- BEGIN FOOTER -->
	<div class="page-footer">
		<div class="page-footer-inner">
			 <?= date("Y") ?> &copy; Web Cables.
		</div>
		<div class="page-footer-tools">
			<span class="go-top">
			<i class="fa fa-angle-up"></i>
			</span>
		</div>
	</div>
	<? } ?>
<!-- END FOOTER -->
</body>
<!-- END BODY -->