                    <div class="container first_breadcrumb position-relative mt-4">
                        <div class="jumbotron px-4 pt-3 pb-2 rounded bg-white shadow-sm">
                            <div class="row">
                                <div class="col-lg-6 col-6">
                                    <p class="bread_cat"><strong>Edit Categories <small class="cat_id">(6059addf56cs5s4s54544ad)</small></strong></p>
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb bread_crumb">
                                            <li><a href="#"><i class="fas fa-home"></i></a></li>
                                            <li> <i class="fas fa-chevron-right mx-3"></i> <a href="#">Categories</a></li>
                                            <li> <i class="fas fa-chevron-right mx-3"></i> Edit</li>
                                        </ol>
                                    </nav>
                                </div>
                                <div class="col-lg-6 col-6">
                                    <div class="form-check form-switch mt-lg-4" style="float: right">
                                        <label class="form-check-label" for="flexSwitchCheckDefault">Active</label>
                                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container second_breadcrumb position-relative mt-4">
                        <div class="jumbotron px-4 pt-3 pb-2 rounded bg-white shadow-sm">
                            <div class="row">
                                <div class="col-lg-6 col-6">
                                    <p class="bread_cat"><strong>Edit Categories <small class="cat_id">(6059addf56cs5s4s54544ad)</small></strong></p>
                                </div>
                                <div class="col-lg-6 col-6">
                                    <div class="form-check form-switch mt-lg-4" style="float: right">
                                        <label class="form-check-label" for="flexSwitchCheckDefault">Active</label>
                                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb bread_crumb text-center d-flex justify-content-center">
                                            <li><a href="#"><i class="fas fa-home"></i></a></li>
                                            <li> <i class="fas fa-chevron-right mx-3"></i> <a href="#">Categories</a></li>
                                            <li> <i class="fas fa-chevron-right mx-3"></i> Edit</li>
                                        </ol>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="input_div">
    <div class="container">
        <div class="jumbotron bg-white shadow-sm py-3 px-3 rounded">
            <form>
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label class="form-label">Image</label>
                            <div class="input-group mb-3">
                                <input type="file" class="form-control" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03" aria-label="Upload">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-3">
                            <label class="form-label">Name * </label>
                            <input type="text" class="form-control" required>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-3">
                            <label class="form-label">Slug *</label>
                            <input type="text" class="form-control" required>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label class="form-label">Parent Category</label>
                            <select class="form-select" aria-label="Default select example">
                                <option value="1">hello</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label class="form-label "><i class="fas fa-info-circle mx-1"></i>Group Categories</label>
                            <select class="form-control multiple-select" multiple>
                                <option value="0">vijay</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <div class="mb-3">
                                <label for="exampleFormControlTextarea1" class="form-label filter_sel">Filterable Attributes</label>
                                <select class="form-control multiple-select" multiple>
                                    <option value="0">vijay</option>
                                    <option value="1">One</option>
                                    <option value="2">Two</option>
                                    <option value="3">Three</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <div class="mb-3">
                                <label for="exampleFormControlTextarea1" class="form-label"> Keywords <small class="text-danger">(Keywords must be in comma(,)seperated)</small></label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="4"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row featured_inp">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="formFile" class="form-label">Featured Brands</label>
                            <input class="form-control" type="file" id="formFile">
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <div class="jumbotron shadow-sm bg-white py-3 my-3 my-lg-0 px-3 my-lg-5 rounded">
            <span class="text-gray-dark">SEO</span>
            <form>
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label class="form-label">Meta Image <span class="meta_img"> it should be at least 600x300 pixels, but 1200x630 or larger is preferred (up to 5MB). stay close to a 1.91:1 aspect ratio to avoid cropping.</span></label>
                            <div class="input-group mb-3">
                                <input type="file" class="form-control" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03" aria-label="Upload">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label class="form-label">Meta Title</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <div class="mb-3">
                                <label class="form-label">Meta Description</label>
                                <textarea class="form-control" rows="3"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <div class="mb-3">
                                <label for="exampleFormControlTextarea1" class="form-label">Meta Keywords </label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    
    <div class="d-flex justify-content-center pt-3 py-lg-0">
        <button type="button" class="btn bsc mx-1">Save Category</button>
        <button type="button" class="btn btl mx-1">Back To List</button>
    </div>
</div>