                            <div class="container position-relative mt-4">
                                <div class="jumbotron px-4 pt-3 rounded bg-white shadow-sm">
                                    <div class="row">
                                        <div class="col-lg-6 col-12">
                                            <p class="bread_cat"><strong>Active Coustomers List</strong></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="active_list">
            <div class="container">
                <div class="jumbotron bg-white shadow-sm px-3 py-3 rounded">
                    <div class="row pb-3">
                        <div class="col-lg-5 col-md-6 col-6">
                            <button type="button" class="btn btn-danger">Deactivate</button>
                        </div>
                        <div class="col-lg-7 col-md-6 col-6">
                            <div class="row">
                                <div class="col-auto">
                                    <p class="row_count">Displaying <strong>1-10</strong> of <strong>40</strong> </p>
                                </div>
                                <div class="col-auto">
                                    <select class="form-select" aria-label="Default select example">
                                        <option value="1">1</option>
                                        <option value="2">10</option>
                                        <option value="3">25</option>
                                        <option value="3">100</option>
                                    </select>
                                </div>
                                <div class="col-auto">
                                    <form class="d-flex">
                                        <input class="form-control me-1" type="search" placeholder="Search" aria-label="Search">
                                        <button class="btn btn-outline-success text-gray-dark" type="submit"><i class="fas fa-search"></i></button>
                                        <button class="btn btn-outline-success text-gray-dark" type="submit"><i class="fas fa-times"></i></button>
                                    </form>
                                </div>
                                <div class="col-auto">
                                    <a href="#"><p class="row_count text-warning mx-1"><i class="fas fa-sliders-h text-warning"></i> Advance Search</p></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive" >
                        <table class="table table-bordered " id="myTable">
                            <thead>
                                <tr class="text-capitalize">
                                    <th scope="col" style="width: 7rem" ></th>
                                    <th scope="col">
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </th>
                                    <th scope="col"><span class="th_name">customername</span></th>
                                    <th scope="col"><span class="th_name">email</span></th>
                                    <th scope="col"><span class="th_name">mobile</span></th>
                                    <th scope="col"><span class="th_name">proffesion</span></th>
                                    <th scope="col"><span class="th_name">Company</span></th>
                                    <th scope="col"><span class="th_name">Website</span></th>
                                    <th scope="col"><span class="th_name">city, state, country</span></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample1">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample2">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample3">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample4">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample5">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample6">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample7">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="collapse" id="collapseExample1">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="collapse" id="collapseExample2">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="collapse" id="collapseExample3">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="collapse" id="collapseExample4">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="collapse" id="collapseExample5">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="collapse" id="collapseExample6">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="collapse" id="collapseExample7">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="py-2">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">Next</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
       