<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <!-- fontawesome -->
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
        <!-- custom css -->
        <link rel="stylesheet" href="css/style.css">
        <!-- datatables -->
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
        
        <title>Arcedior : Input Field</title>
    </head>
    <body>
        <div class="list_header">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-6 my-3">
                        <img src="img/logo.svg" class="img-fluid img_logo " alt="Arcedior">
                    </div>
                    <div class="col-md-6 col-6 my-3">
                        <div class="d-flex justify-content-lg-end justify-content-around">
                            <div class="btn-group">
                                <button class="btn btn-sm dropdown-toggle text-white" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Masters
                                </button>
                                <ul class="dropdown-menu text-capitalize" aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" href="#">Hello</a></li>
                                    <li><a class="dropdown-item" href="#">new projects</a></li>
                                    <li><a class="dropdown-item" href="#">testing a new project</a></li>
                                </ul>
                            </div>
                            <i class="fas fa-expand text-white mx-lg-4 mt-2 mt-lg-1"></i>
                            <img src="img/user_icon.svg" class="user_icon img-thumbnail img-fluid rounded rounded-circle">
                        </div>
                    </div>
                </div>
            </div>
            <nav class="navbar navbar-expand-lg nav_menu">
                <div class="container">
                    <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-capitalize">
                            <li class="nav-item ">
                                <a class="nav-link nav_text" aria-current="page" href="#">Home</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link nav_text dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    brand
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#">Action</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                            </li>
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link nav_text" aria-current="page" href="#">categorise</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link nav_text dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        products
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                    </ul>
                                </li>
                                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                    <li class="nav-item">
                                        <a class="nav-link nav_text" aria-current="page" href="#">projects</a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link nav_text dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            sites
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <li><a class="dropdown-item" href="#">Action</a></li>
                                            <li><a class="dropdown-item" href="#">Another action</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link nav_text dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            forms
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <li><a class="dropdown-item" href="#">Action</a></li>
                                            <li><a class="dropdown-item" href="#">Another action</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link nav_text dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            customers
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <li><a class="dropdown-item" href="#">Action</a></li>
                                            <li><a class="dropdown-item" href="#">Another action</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link nav_text" aria-current="page" href="#">RFQs</a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link nav_text dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            project BOQs
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <li><a class="dropdown-item" href="#">Action</a></li>
                                            <li><a class="dropdown-item" href="#">Another action</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link nav_text dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            reports
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <li><a class="dropdown-item" href="#">Action</a></li>
                                            <li><a class="dropdown-item" href="#">Another action</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link nav_text" aria-current="page" href="#">cashe</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link nav_text" aria-current="page" href="#">orders</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link nav_text" aria-current="page" href="#">affiliate</a>
                                    </li>
                                </div>
                            </nav>
                            <div class="container position-relative mt-4">
                                <div class="jumbotron px-4 pt-3 rounded bg-white shadow-sm">
                                    <div class="row">
                                        <div class="col-lg-6 col-12">
                                            <p class="bread_cat"><strong>Active Coustomers List</strong></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="active_list">
            <div class="container">
                <div class="jumbotron bg-white shadow-sm px-3 py-3 rounded">
                    <div class="row pb-3">
                        <div class="col-lg-5 col-md-6 col-6">
                            <button type="button" class="btn btn-danger">Deactivate</button>
                        </div>
                        <div class="col-lg-7 col-md-6 col-6">
                            <div class="row">
                                <div class="col-auto">
                                    <p class="row_count">Displaying <strong>1-10</strong> of <strong>40</strong> </p>
                                </div>
                                <div class="col-auto">
                                    <select class="form-select" aria-label="Default select example">
                                        <option value="1">1</option>
                                        <option value="2">10</option>
                                        <option value="3">25</option>
                                        <option value="3">100</option>
                                    </select>
                                </div>
                                <div class="col-auto">
                                    <form class="d-flex">
                                        <input class="form-control me-1" type="search" placeholder="Search" aria-label="Search">
                                        <button class="btn btn-outline-success text-gray-dark" type="submit"><i class="fas fa-search"></i></button>
                                        <button class="btn btn-outline-success text-gray-dark" type="submit"><i class="fas fa-times"></i></button>
                                    </form>
                                </div>
                                <div class="col-auto">
                                   <a href="#"><p class="row_count text-warning mx-1"><i class="fas fa-sliders-h text-warning"></i> Advance Search</p></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive" >
                        <table class="table table-bordered " id="myTable">
                            <thead>
                                <tr class="text-capitalize">
                                    <th scope="col" style="width: 7rem" ></th>
                                    <th scope="col">
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </th>
                                    <th scope="col"><span class="th_name">customername</span></th>
                                    <th scope="col"><span class="th_name">email</span></th>
                                    <th scope="col"><span class="th_name">mobile</span></th>
                                    <th scope="col"><span class="th_name">proffesion</span></th>
                                    <th scope="col"><span class="th_name">Company</span></th>
                                    <th scope="col"><span class="th_name">Website</span></th>
                                    <th scope="col"><span class="th_name">city, state, country</span></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample1">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample2">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>

                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample3">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>

                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample4">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>

                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample5">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>

                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample6">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>

                                <tr>
                                    <td>
                                        <div class="tab_icn rounded py-1 px-4 px-lg-0 d-flex justify-content-around">
                                            <a href="edit.php"><i class="fas fa-pencil-alt"></i></a>
                                            <a data-toggle="collapse" href="#collapseExample7">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href=""> <i class="fas fa-sign-out-alt"></i></a>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-check d-flex justify-content-center">
                                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                                        </div>
                                    </td>
                                    <td class="text-capitalize"> <span class="td_name"> Vijay </span> </td>
                                    <td> <span class="td_name"> vjlathiya@gmail.com </span> </td>
                                    <td> <span class="td_name"> 7698343511 </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> Devloper </span> </td>
                                    <td class="text-capitalize"> <span class="td_name"> abc </span> </td>
                                    <td> <span class="td_name"> www.abc.com </span></td>
                                    <td class="text-capitalize"> <span class="td_name"> somnath, gujarat, india </span> </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="collapse" id="collapseExample1">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="collapse" id="collapseExample2">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="collapse" id="collapseExample3">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="collapse" id="collapseExample4">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="collapse" id="collapseExample5">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="collapse" id="collapseExample6">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="collapse" id="collapseExample7">
                        <div class="card card-body">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link active tab_nav_link" id="ProjectsBoQs-tab" data-toggle="tab" href="#ProjectsBoQs" role="tab" aria-controls="home" aria-selected="true">ProjectsBoQs <span class="badge text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="RFQs-tab" data-toggle="tab" href="#RFQs" role="tab" aria-controls="home" aria-selected="true">RFQs <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Favourites-tab" data-toggle="tab" href="#Favourites" role="tab" aria-controls="home" aria-selected="true">Favourites <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Catalogues-tab" data-toggle="tab" href="#Catalogues" role="tab" aria-controls="home" aria-selected="true">Catalogues <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a class="nav-link tab_nav_link" id="Search-tab" data-toggle="tab" href="#Search" role="tab" aria-controls="home" aria-selected="true">Search History <span class="badge badge-dark text-dark">0</span></a>
                                </li>
                            </ul>
                            <div class="tab-content mt-3 mt-lg-4" id="myTabContent">
                                <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr class="text-capitalize">
                                                    <th scope="col"><span class="th_name">name</span></th>
                                                    <th scope="col"><span class="th_name">#products</span></th>
                                                    <th scope="col"><span class="th_name">project type</span></th>
                                                    <th scope="col"><span class="th_name">is deleted</span></th>
                                                    <th scope="col"><span class="th_name">is shered</span></th>
                                                    <th scope="col"><span class="th_name">created on</span></th>
                                                    <th scope="col"><span class="th_name">updated on</span></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="RFQs" role="tabpanel" aria-labelledby="RFQs-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Catalogues" role="tabpanel" aria-labelledby="Catalogues-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Favourites" role="tabpanel" aria-labelledby="Favourites-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Search" role="tabpanel" aria-labelledby="Search-tab">
                                    <div class="tab-pane fade show active" id="ProjectsBoQs" role="tabpanel" aria-labelledby="ProjectsBoQs-tab">
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr class="text-capitalize">
                                                        <th scope="col"><span class="th_name">name</span></th>
                                                        <th scope="col"><span class="th_name">#products</span></th>
                                                        <th scope="col"><span class="th_name">project type</span></th>
                                                        <th scope="col"><span class="th_name">is deleted</span></th>
                                                        <th scope="col"><span class="th_name">is shered</span></th>
                                                        <th scope="col"><span class="th_name">created on</span></th>
                                                        <th scope="col"><span class="th_name">updated on</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center mt-3">
                                    <button type="button" class="btn btn-success  text-white d-flex justify-content-around">View All</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="py-2">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">Next</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <footer class="pt-2">
            <p class="text-center footer">2021 &copy;  Arcedior</p>
        </footer>
        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
        <!-- jquery -->
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <!-- datatables -->
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
        <script>
        $(document).ready( function () {
        $('#myTable').DataTable();
        } );
        </script>
    </body>
</html>